name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: npm run package

      - name: List Build Directory
        run: |
          dir
          dir dist
          dir dist/xe_web_crm
          dir dist/xe_web_crm/browser

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            release/**/*.exe
            release/**/*.zip
            release/latest.yml
            release/**/*.yml
            release/**/*.yaml 